travis:
  secure:
    BINSTAR_TOKEN: eu41ZBukXw4Lky/omIYpFJ4TxX12ABWNdocemr/+m+gtbhtt3ACD8lvy7ehaHoJeSDRfZezHzsMqsfRMRCxKp/rCCcf8m4XPT1tNKS8hk9MgSeAaGZx1EeOStj4rY1w+DimublzCVSg3TWtSuZoJeHzAZDc6VeQSlMe6MbA54/IDPZiLX4BsUKSPHcOE6wgPQcCfbMO6nJshvp/zwbHio8DjTQV5mpxZox5PyKal/0e/s6Vr4HEBrDYQLMUqmZ2g1PcaCRZzq6HQvuZD9tdA6M1CRFHUx+CAaYmQoEAxUtnx9p6ZcPqr+4d9RC3yEQvQNkJyRB7VmpFvJBBEqbkDCgLIcyR4AWVphttAWyfGSP6sfStEY1h+jyKlcr9L1LNZy854Cqtly/O+1Ekgs+VjZDMyQAgTzSPKVj4UrJrw56JEVLMjB9TafiZ95RKCdOwlt5/si3wV9noGUSHLuctnH4ciBZIlpAa/Po45n37IX5VI1gaw1kfJJ700Uqb/I3gBjw5O4Xg+fuPq9YabtlWo+2iff+irOjIgMqHmiqY1eks4J3AaYkXr+DHzmzYrOkdlwZr3XkKElazKun0Tv/ZmHmdhzqUWkQ/gfcizJiaDajKjJ7mG48MeZ7uWMnUFzPS4wAiAzFW0iL2bTaMN25Kf8MtvEJ4T1ZkVvXj9NHHUFuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
